---
services:
  linker:
    image: ghcr.io/daniel-mizsak/linker:latest
    restart: unless-stopped
    networks:
      - postgres
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.linker.rule=Host(`linker.mlops.top`)"
      - "traefik.http.routers.linker.entrypoints=websecure"
      - "traefik.http.routers.linker.tls.certresolver=production"
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      LINKER_TOKEN: ${LINKER_TOKEN}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

networks:
  postgres:
    external: true
  traefik:
    external: true
