"""
Constants used in the application.

@author "Daniel Mizsak" <info@pythonvilag.hu>
"""

# General
LINKER_TOKEN_KEY = "LINKER_TOKEN"  # noqa: S105

# PostgreSQL
POSTGRES_HOST_KEY = "POSTGRES_HOST"
POSTGRES_PORT_KEY = "POSTGRES_PORT"
POSTGRES_DATABASE_KEY = "POSTGRES_DATABASE"
POSTGRES_USERNAME_KEY = "POSTGRES_USERNAME"
POSTGRES_PASSWORD_KEY = "POSTGRES_PASSWORD"  # noqa: S105
